server:
  port: 7892
spring:
  application:
    name: zq-user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/storedemo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&&useSSL=false
    username: root
    password: yesiwant
#rabbitmq:   #rabbitmq端口说明：5672-amqp，25672-clustering，61613-stomp，1883-mqtt
#    username: guest
#    password: guest
#    addresses: 127.0.0.1:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7890/eureka
    # eureka客户端从eureka服务器注册表中获取服务注册信息的时间间隔（s），默认为30秒,开发阶段调小
    registry-fetch-interval-seconds: 30
#mybatis 别名配置
mybatis.type-aliases-package: com.zq.user.entity
